#!/usr/bin/env python3
"""Simplified Gmail OAuth setup that saves to .env file."""

import os
import json
from pathlib import Path
from google_auth_oauthlib.flow import InstalledAppFlow

# Gmail API scopes
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

# Project root
project_root = Path(__file__).parent.parent
env_file = project_root / ".env"


def print_instructions():
    """Print setup instructions."""
    print("=" * 70)
    print("Simplified Gmail API Setup")
    print("=" * 70)
    print()
    print("Before running this script:")
    print()
    print("1. Go to: https://console.cloud.google.com/")
    print("2. Create a new project (or select existing)")
    print("3. Enable the Gmail API:")
    print("   - Navigate to 'APIs & Services' > 'Library'")
    print("   - Search for 'Gmail API'")
    print("   - Click 'Enable'")
    print("4. Create OAuth 2.0 credentials:")
    print("   - Navigate to 'APIs & Services' > 'Credentials'")
    print("   - Click 'Create Credentials' > 'OAuth client ID'")
    print("   - Application type: 'Desktop app'")
    print("   - Download the credentials JSON file")
    print("5. Save it as 'credentials.json' in the project root")
    print()
    print("This script will:")
    print("- Read credentials.json")
    print("- Open browser for OAuth authorization")
    print("- Save all credentials to .env file")
    print()
    print("=" * 70)
    print()


def get_oauth_credentials():
    """Run OAuth flow and get credentials."""
    creds_file = project_root / "credentials.json"

    if not creds_file.exists():
        print(f"ERROR: credentials.json not found at {creds_file}")
        print()
        print("Please download OAuth credentials from Google Cloud Console")
        print("and save as 'credentials.json' in the project root.")
        return None

    print(f"✓ Found credentials file: {creds_file}")
    print()
    print("Starting OAuth flow...")
    print("A browser window will open. Please authorize the application.")
    print()

    try:
        flow = InstalledAppFlow.from_client_secrets_file(str(creds_file), SCOPES)
        creds = flow.run_local_server(port=0)

        print("✓ Authorization successful!")
        return creds
    except Exception as e:
        print(f"✗ OAuth flow failed: {e}")
        return None


def save_to_env(creds, credentials_file):
    """Save credentials to .env file."""
    # Read the credentials.json to get client details
    with open(credentials_file, 'r') as f:
        client_config = json.load(f)

    # Extract client info
    if 'installed' in client_config:
        client_info = client_config['installed']
    elif 'web' in client_config:
        client_info = client_config['web']
    else:
        print("ERROR: Unexpected credentials format")
        return False

    # Read existing .env if it exists
    env_content = ""
    if env_file.exists():
        with open(env_file, 'r') as f:
            env_content = f.read()

    # Remove old Gmail OAuth entries if they exist
    lines = env_content.split('\n')
    new_lines = []
    skip_section = False

    for line in lines:
        if line.strip().startswith('# Gmail OAuth Configuration'):
            skip_section = True
            continue
        if skip_section and line.strip() and not line.strip().startswith('GMAIL_'):
            skip_section = False
        if not skip_section:
            new_lines.append(line)

    env_content = '\n'.join(new_lines).strip()

    # Add Gmail OAuth configuration
    gmail_config = f"""

# Gmail OAuth Configuration (Auto-generated by setup_gmail_simple.py)
GMAIL_CLIENT_ID={client_info.get('client_id', '')}
GMAIL_CLIENT_SECRET={client_info.get('client_secret', '')}
GMAIL_REFRESH_TOKEN={creds.refresh_token}
GMAIL_TOKEN_URI={client_info.get('token_uri', 'https://oauth2.googleapis.com/token')}
"""

    env_content += gmail_config

    # Write to .env
    with open(env_file, 'w') as f:
        f.write(env_content)

    print(f"✓ Credentials saved to {env_file}")
    return True


def main():
    """Main setup flow."""
    print_instructions()

    credentials_file = project_root / "credentials.json"

    # Get OAuth credentials
    creds = get_oauth_credentials()
    if not creds:
        print("\nSetup failed.")
        return

    # Save to .env
    if not save_to_env(creds, credentials_file):
        print("\nFailed to save credentials to .env")
        return

    print()
    print("=" * 70)
    print("Setup Complete!")
    print("=" * 70)
    print()
    print("Your Gmail OAuth credentials are now in .env")
    print()
    print("Next steps:")
    print("1. Add your AI API key to .env:")
    print("   ANTHROPIC_API_KEY=sk-ant-your-key")
    print("   (or OPENAI_API_KEY=sk-your-key)")
    print("2. Run the Streamlit app:")
    print("   streamlit run streamlit_app.py")
    print()


if __name__ == "__main__":
    main()
